//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolKumyshbaevaApp.ModelsConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTypePartner { get; set; }
        public string NameCompany { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string SNPdirector { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public byte[] Logo { get; set; }
        public string Raiting { get; set; }
        public string PointSale { get; set; }
        public string HistoryRealize { get; set; }
    
        public virtual TypePartner TypePartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
    }
}
