//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolKumyshbaevaApp.ModelsConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int Id { get; set; }
        public string Articul { get; set; }
        public Nullable<int> IdTypeProduct { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<double> PartnerMinCost { get; set; }
        public Nullable<double> SizeBox { get; set; }
        public Nullable<double> WeightWithoutBox { get; set; }
        public Nullable<double> WeightWithBox { get; set; }
        public string SertificateQuality { get; set; }
        public string NumberOfStandart { get; set; }
        public string HistoryPartnerMinCost { get; set; }
        public string TimeOfMade { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<int> NumberWorkshop { get; set; }
        public Nullable<int> CountPeopleInWorkshop { get; set; }
        public string NecessaryMaterials { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
